application: bradfitz-brackup
version: 1
api_version: 1
runtime: python

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

# Post URL must not be accessible by any users.  Only by
# going through Blobstore API upload URL.
- url: /post
  script: main.py

- url: .*
  script: main.py

